import { DivisionConfig, DivisionId } from '../types';
import { COMPANY_INFO } from './company';

export const DIVISIONS: Record<DivisionId, DivisionConfig> = {
  sws: {
    id: 'sws',
    name: 'SWS Event Management',
    shortName: 'SWS Events',
    tagline: 'Creating Moments... Luxury Event & Stage Decorations',
    description:
      'The primary flagship division of Mahdev Pvt Ltd. Comprehensive event management, luxury wedding stage & mandap decorations, full furniture and equipment rentals, concert AV production, and high-impact celebrations.',
    badge: 'Primary Flagship Division',
    isPrimary: true,
    route: '/sws',
    domainUrl: 'https://mahdev.lk/sws',
    accentColor: '#0052FF',
    gradient: 'from-[#0052FF] to-[#0A1E5C]',
    image: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
    imageUrl: 'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=85',
    heroHeadline: 'Immersive Event Decor, Grand Staging & Equipment Rentals',
    heroSubheadline:
      'From luxury wedding mandaps, floral stage decor, and full event furniture/AV rentals to grand summits and concert arenas, SWS is Mahdev’s primary flagship division.',
    iconName: 'Sparkles',
    contactEmail: COMPANY_INFO.email,
    contactPhone: '075 092 8078',
    aboutHeading: 'The Art of Extraordinary Celebrations',
    aboutText: 'SWS Event Management transforms landmark visions into grand realities across Sri Lanka. Combining architectural mandaps, high-density floral artistry, and cutting-edge stage engineering, we ensure unforgettable moments.',
    mission: 'To craft immersive sensory event environments that honor tradition while pioneering modern aesthetic luxury.',
    vision: 'To be the preeminent luxury event management institution in South Asia recognized for bespoke craftsmanship.',
    coreServices: [
      {
        title: 'Luxury Wedding & Stage Decorations',
        description: 'Bespoke floral mandaps, grand stage backdrops, fairy-light canopies, and luxury head table decor.',
        iconName: 'Heart',
      },
      {
        title: 'Event Equipment & Furniture Rentals',
        description: 'Chiavari chairs, banquet tables, luxury lounges, truss structures, staging platforms, and power generators.',
        iconName: 'Grid',
      },
      {
        title: 'Audio, Visual & Lighting Engineering',
        description: 'Concert-grade acoustics, intelligent moving heads, Ultra-HD LED video walls, special FX, and live broadcasting.',
        iconName: 'Volume2',
      },
      {
        title: 'Conferences, Summits & Turnkey Packages',
        description: 'Keynote staging, executive summits, end-to-end event planning, gourmet catering, and master coordination.',
        iconName: 'Building2',
      },
    ],
    stats: [
      { label: 'Events & Decors Curated', value: '450+' },
      { label: 'Rental Inventory Units', value: '5,000+' },
      { label: 'Production Satisfaction', value: '99.4%' },
    ],
  },
  u1: {
    id: 'u1',
    name: 'U1 Studio',
    shortName: 'U1 Studio',
    tagline: 'Capturing Memories... Fine Art Photography & Cinema',
    description:
      'High-end wedding photography, candid photojournalism, 8K cinema videography, studio fashion portraits, pre-shoots, and aerial drone coverage with fine-art post-production mastering.',
    badge: 'Photography & Cinema',
    route: '/u1',
    domainUrl: 'https://mahdev.lk/u1',
    accentColor: '#0066FF',
    gradient: 'from-[#0066FF] to-[#061033]',
    image: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=1200&q=85',
    imageUrl: 'https://images.unsplash.com/photo-1537633552985-df8429e8048b?auto=format&fit=crop&w=1200&q=85',
    heroHeadline: 'High-End Photography & Cinematic Visual Storytelling',
    heroSubheadline:
      'Mastering the delicate harmony between natural light, fine-art composition, and cutting-edge 8K cinema gear to immortalize your sacred milestones forever.',
    iconName: 'Camera',
    contactEmail: COMPANY_INFO.email,
    contactPhone: '075 092 8078',
    aboutHeading: 'Immortalizing Milestones with Fine-Art Precision',
    aboutText: 'U1 Studio operates at the vanguard of modern visual documentation. Our master cinema directors, lighting masters, and fine-art portraitists preserve life’s most sacred milestones with emotional authenticity and 8K HDR fidelity.',
    mission: 'To elevate every candid emotion and sacred ritual into timeless visual poetry.',
    vision: 'To establish Sri Lanka’s premier cinematic studio renowned globally for fine-art wedding storytelling.',
    coreServices: [
      {
        title: 'Luxury Wedding Photography',
        description: 'Editorial-grade portraits, candid photojournalism, and handcrafted fine-art keepsake albums.',
        iconName: 'Camera',
      },
      {
        title: '8K Cinematic Wedding Films & Adverts',
        description: 'Cinema-grade storytelling, color-graded wedding trailers, commercial films, and documentary reels.',
        iconName: 'Film',
      },
      {
        title: 'Studio Portraiture & Fashion',
        description: 'Controlled high-end studio lighting, fashion editorials, and executive headshot mastery.',
        iconName: 'UserCheck',
      },
      {
        title: 'Aerial Drone & Pre-Shoot Cinematography',
        description: 'Licensed aerial surveying, romantic pre-wedding shoots, and dramatic landscape perspectives.',
        iconName: 'Compass',
      },
    ],
    stats: [
      { label: 'Stories Captured', value: '850+' },
      { label: 'Cinematic Awards', value: '18' },
      { label: 'Deliverable Fidelity', value: '8K HDR' },
    ],
  },
  it: {
    id: 'it',
    name: 'Mahdev IT Solutions',
    shortName: 'IT Solutions',
    tagline: 'Delivering Innovation... Scalable IT Solutions & Cloud',
    description:
      'Enterprise software engineering, modern cloud architecture, scalable web and mobile ecosystems, intelligent automation, and cybersecurity assurance.',
    badge: 'IT Solutions & Tech',
    route: '/it',
    domainUrl: 'https://mahdev.lk/it',
    accentColor: '#0052FF',
    gradient: 'from-[#0052FF] to-[#0A1E5C]',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=85',
    imageUrl: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=1200&q=85',
    heroHeadline: 'Engineering Scalable IT Solutions & Digital Ecosystems',
    heroSubheadline:
      'We architect mission-critical software, intuitive web platforms, and automated cloud workflows that empower modern enterprises to scale without limits.',
    iconName: 'Cpu',
    contactEmail: COMPANY_INFO.email,
    contactPhone: '075 092 8078',
    aboutHeading: 'Architecting Resilient Digital Futures',
    aboutText: 'Mahdev IT Solutions delivers mission-critical software engineering, cloud transformations, and custom enterprise ecosystems that drive scalable digital dominance for forward-looking organizations.',
    mission: 'To build high-performance software and cloud infrastructures engineered for uncompromising scale and security.',
    vision: 'To be the strategic technology catalyst empowering enterprises to dominate global digital markets.',
    coreServices: [
      {
        title: 'Custom Web & Mobile Applications',
        description: 'High-performance React, Next.js, and native mobile development engineered with type-safe precision.',
        iconName: 'Code',
      },
      {
        title: 'Cloud Infrastructure & DevOps',
        description: 'Automated CI/CD pipelines, container orchestration, multi-region failover, and microservice mesh.',
        iconName: 'Cloud',
      },
      {
        title: 'Enterprise ERP & Systems Integration',
        description: 'Unified business operations, custom ERP connectors, CRM pipelines, and real-time inventory systems.',
        iconName: 'Layers',
      },
      {
        title: 'Cybersecurity & Infrastructure Audits',
        description: 'Penetration testing, compliance standards verification, and 24/7 proactive security monitoring.',
        iconName: 'ShieldCheck',
      },
    ],
    stats: [
      { label: 'IT Solutions Deployed', value: '140+' },
      { label: 'Uptime Reliability', value: '99.99%' },
      { label: 'Code Quality Benchmark', value: 'A+' },
    ],
  },
  travels: {
    id: 'travels',
    name: 'Mahdev Travels',
    shortName: 'Mahdev Travels',
    tagline: 'Curating Journeys... Bespoke Island Escapes & VIP Expeditions',
    description:
      'Bespoke travel curation, VIP executive retreats, luxury island expeditions, chauffeur services, and personalized global holiday itineraries.',
    badge: 'Travel & Expeditions',
    route: '/travels',
    domainUrl: 'https://mahdev.lk/travels',
    accentColor: '#0052FF',
    gradient: 'from-[#0052FF] to-[#061033]',
    image: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85',
    imageUrl: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=85',
    heroHeadline: 'Tailored Journeys Across Extraordinary Horizons',
    heroSubheadline:
      'Experience unmatched hospitality, handpicked heritage villas, private charters, and guided expeditions designed with flawless logistics.',
    iconName: 'Plane',
    contactEmail: COMPANY_INFO.email,
    contactPhone: '075 092 8078',
    aboutHeading: 'Unlocking Extraordinary Island Horizons',
    aboutText: 'Mahdev Travels curates bespoke travel expeditions and VIP executive retreats. We combine five-star private sanctuary bookings, private helicopter transfers, and discreet chauffeur services.',
    mission: 'To connect global travelers with the deepest soul of Sri Lanka through unparalleled luxury and private access.',
    vision: 'To be the most coveted bespoke luxury expedition brand in the Indian Ocean.',
    coreServices: [
      {
        title: 'Bespoke Island & Heritage Tours',
        description: 'Handcrafted itineraries revealing Sri Lanka and global gems with private historian guides.',
        iconName: 'MapPin',
      },
      {
        title: 'Executive Retreats & VIP Transport',
        description: 'Executive fleet logistics, discreet luxury shuttles, and curated offsite venues.',
        iconName: 'Car',
      },
      {
        title: 'Luxury Villa & Resort Reservations',
        description: 'Exclusive access to premier private estates, beachfront chalets, and 5-star mountain sanctuaries.',
        iconName: 'Home',
      },
      {
        title: 'Adventure & Eco Expeditions',
        description: 'Ethical wildlife safaris, scenic helicopter transfers, and deep blue catamaran sailing.',
        iconName: 'Compass',
      },
    ],
    stats: [
      { label: 'Bespoke Itineraries', value: '1,200+' },
      { label: 'Destinations Covered', value: '35+' },
      { label: 'Client Satisfaction', value: '99.8%' },
    ],
  },
  mart: {
    id: 'mart',
    name: 'Mahdev Online Mart',
    shortName: 'Mahdev Mart',
    tagline: 'Curated Commerce... Event Decor & Smart Tech',
    description:
      'Curated e-commerce storefront delivering bespoke event & home decor, ambient stage lighting, creator electronics, and smart tech accessories.',
    badge: 'Decor & Smart Tech',
    route: '/mart',
    domainUrl: 'https://mahdev.lk/mart',
    accentColor: '#0052FF',
    gradient: 'from-[#0052FF] to-[#0A1E5C]',
    image: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=85',
    imageUrl: 'https://images.unsplash.com/photo-1513151233558-d860c5398176?auto=format&fit=crop&w=1200&q=85',
    heroHeadline: 'Curated Event Decor & Smart Tech Hardware',
    heroSubheadline:
      'Explore bespoke event decor, ambient stage lighting, studio creator accessories, and authenticated tech hardware with island-wide logistics.',
    iconName: 'ShoppingBag',
    contactEmail: COMPANY_INFO.email,
    contactPhone: '075 092 8078',
    aboutHeading: 'Curated Decor & Smart Tech for Creators & Venues',
    aboutText: 'Mahdev Online Mart is the trusted commerce ecosystem for curated event & home decor, ambient stage lighting, studio audio gear, and smart tech electronics with island-wide express delivery.',
    mission: 'To deliver exceptional event aesthetics and modern technological gear backed by verified authenticity and reliable service.',
    vision: 'To be Sri Lanka’s premier digital commerce destination for event styling decor and modern creator tech.',
    coreServices: [
      {
        title: 'Curated Event & Interior Decor',
        description: 'Luxury candelabras, floral arch backdrops, handcrafted brass lamps, and artisanal ceramics.',
        iconName: 'Sparkles',
      },
      {
        title: 'Express Nationwide Delivery',
        description: 'Real-time parcel tracking, secure packaging, and same-day priority dispatch in metro hubs.',
        iconName: 'Truck',
      },
      {
        title: 'Enterprise Procurement Solutions',
        description: 'Bulk enterprise orders, customized billing, tax invoices, and dedicated account reps.',
        iconName: 'Briefcase',
      },
      {
        title: 'Guaranteed Buyer Protection',
        description: 'Hassle-free 7-day return policy, verified authentic product batches, and local service support.',
        iconName: 'CheckCircle2',
      },
    ],
    stats: [
      { label: 'Products Curated', value: '2,500+' },
      { label: 'Orders Dispatched', value: '45k+' },
      { label: 'Authenticity Guarantee', value: '100%' },
    ],
  },
};

export const DIVISION_LIST: DivisionConfig[] = Object.values(DIVISIONS);
